# ==============================================================================
# 网格交易完整配置文件（做多方向）
# ==============================================================================
# 
# 🎯 当前配置：价格移动网格 + 四重保护（剥头皮 + 本金保护 + 止盈 + 价格锁定）
# 
# 📋 本文件包含所有网格模式，需要切换时取消对应注释即可：
#    ✅ 价格移动网格（当前启用）
#    📝 固定范围网格（注释中，可启用）
#    📝 马丁模式（注释中，可启用）
# 
# ==============================================================================

grid_system:
  # ============================================================================
  # 基础配置
  # ============================================================================
  exchange: "backpack"
  symbol: "HYPE_USDC_PERP"
  
  # ----------------------------------------------------------------------------
  # 网格类型选择（三选一，其他两个需注释）
  # ----------------------------------------------------------------------------
  grid_type: "follow_long"         # ✅ 当前：价格移动做多网格
  # grid_type: "long"              # 📝 备选：固定范围做多网格
  # grid_type: "martingale_long"   # 📝 备选：固定范围做多马丁网格
  
  # ============================================================================
  # 价格移动网格参数（grid_type = "follow_long" 时生效）
  # ============================================================================
  follow_grid_count: 200      # 总共200个网格
  follow_timeout: 300         # 脱离超时5分钟
  follow_distance: 2          # 脱离距离2格
  price_offset_grids: 5       # 🆕 价格偏移网格数（默认0）
  # 说明：调整网格启动时的价格边界位置，让当前价格处于网格内部
  # - 默认值0：以当前价格为边界（旧行为）
  # - 做多网格：当前价格 + 5格 = 上边界，然后向下计算下边界
  #           例如：当前价格$100，grid_interval=$0.04，则上边界=$100.20
  #                 网格范围：$92.20（下边界）~ $100.20（上边界）
  #                 当前价格$100在网格内部，可立即触发买单
  # - 做空网格：当前价格 - 5格 = 下边界，然后向上计算上边界
  # - 推荐值：3-10格（让当前价格处于网格内部靠近边界的位置）
  # - 适用场景：所有重置（剥头皮、脱离、止盈）都使用此配置
  
  # ----------------------------------------------------------------------------
  # 固定范围网格参数（grid_type = "long" 或 "martingale_long" 时生效）
  # 需要启用固定范围网格时，取消下面3行注释，并注释掉上面的follow参数
  # ----------------------------------------------------------------------------
  # lower_price: 1.90          # 📝 网格下限价格
  # upper_price: 2.30          # 📝 网格上限价格
  # # 网格数量会根据 (upper_price - lower_price) / grid_interval 自动计算
  
  # ============================================================================
  # 通用网格参数（所有网格类型都需要）
  # ============================================================================
  grid_interval: 0.04        # 每格间隔$0.002
  order_amount: 0.5           # 每格基础数量 5.0 ASTER
    # ----------------------------------------------------------------------------
  # 交易精度配置（重要！影响订单数量格式化）
  # ----------------------------------------------------------------------------
  quantity_precision: 2     # 📝 BNB数量精度为3位小数（0.001）
  #                         # 💡 不同代币精度不同：
  #                         #    BTC=8位(0.00000001), ETH=6位(0.000001)
  #                         #    BNB=3位(0.001), SOL=4位(0.0001)
  #                         # ⚠️ 此参数必须与交易所实际精度一致！
  #                         #    否则健康检查会误报持仓异常
  # ----------------------------------------------------------------------------
  # 马丁模式参数（grid_type = "martingale_long" 时生效）
  # 需要启用马丁模式时，取消下面1行注释
  # ----------------------------------------------------------------------------
  martingale_increment: 0.01  # 📝 马丁递增数量（每格增加0.5 ASTER）
  #                            #    例如：第1格5.0, 第2格5.5, 第3格6.0...
  
  # 🎯 剥头皮模式配置（第一道防线）
  scalping_enabled: true               # ✅ 启用剥头皮
  scalping_trigger_percent: 15         # 🔔 触发阈值90%（从顶部往下跌90%时触发）
  scalping_take_profit_grids: 2        # 📊 止盈2格（向上2格）
  # 说明：90% = 从Grid 200往下跌到Grid 20（200 - 200*90% = 20）
  
  # 🛡️ 本金保护模式配置（第二道防线）
  capital_protection_enabled: true     # ✅ 启用本金保护
  capital_protection_trigger_percent: 40  # 🔔 触发阈值1%（从顶部往下跌1%时触发）
  # 说明：1% = 从Grid 200往下到Grid 198（200 - 200*1% = 198）
  #      40% = 从Grid 200往下到Grid 120（200 - 200*40% = 120）
  # ⚠️ 测试用可设置1-5%（轻微下跌即触发），实战建议40-50%
  
  # 💰 止盈模式配置（盈利保护）
  take_profit_enabled: true            # ✅ 启用止盈模式
  take_profit_percentage: 0.002        # 🎯 止盈阈值0.5%（盈利超过本金0.5%时止盈）
  
  # 🔒 价格锁定模式配置（智能冻结）
  price_lock_enabled: true             # ✅ 启用价格锁定模式
  price_lock_threshold: 50.0            # 🎯 锁定价格阈值 $2.50（价格向上脱离且>=阈值时锁定）
  price_lock_start_at_threshold: false  # 🆕 启动时使用阈值作为起点（仅价格移动网格FOLLOW模式生效）
  # 说明：
  # - true: 如果启动时当前价格 > 阈值，则以阈值为网格上限（期望在更低价格区间启动）
  # - false: 始终以当前价格为网格起点（默认行为）
  # - 仅对价格移动网格（FOLLOW_LONG/FOLLOW_SHORT）生效，普通网格忽略此参数
  
  # 做多网格说明：
  # - 当价格向上脱离网格范围时（盈利方向）
  # - 如果价格 >= $2.50，则冻结网格（不平仓止盈）
  # - 保留订单和持仓，等待价格回落
  # - 价格回到网格范围内时，自动解除冻结
  
  # 🎯 反手挂单格子距离配置（利润优化）
  reverse_order_grid_distance: 1       # 🔥 反手挂单距离（默认1格，可自定义提高利润）
  # 说明：成交后反手挂单的格子距离
  # - 默认值1：买单成交@$2.00 → 卖单挂@$2.01（间隔1格）
  # - 设置为2：买单成交@$2.00 → 卖单挂@$2.02（间隔2格，利润提高）
  # - 设置为3：买单成交@$2.00 → 卖单挂@$2.03（间隔3格，利润更高）
  # - 推荐范围：1-5格（格数越高利润越大，但成交概率降低）
  # - 适用场景：震荡行情可适当提高，单边行情保持默认值
  
  # 🔍 订单健康检查间隔配置（系统维护）
  order_health_check_interval: 300     # 🕐 健康检查间隔（秒，默认300秒=5分钟）
  # 说明：定期检查订单健康状态
  # - 默认值：300秒（5分钟）
  # - 推荐范围：180-600秒（3-10分钟）
  # - 设置太短：频繁检查，可能影响性能
  # - 设置太长：问题发现不及时
  # - 实战建议：300-600秒（5-10分钟）
  
  # 四重保护说明（做多方向）：
  # 1. 剥头皮（90%）：价格从Grid 200下跌到Grid 20（下跌90%）→ 取消卖单 → 挂止盈卖单 → 止盈成交后重置
  # 2. 本金保护（1%）：价格从Grid 200下跌到Grid 198（下跌1%）→ 等待抵押品回本 → 回本后重置
  # 3. 止盈模式（0.5%）：盈利超过本金0.5% → 平仓 → 重置网格
  # 4. 价格锁定（$2.20）：价格向上脱离 >= $2.20 → 冻结网格 → 等待价格回归
  # 
  # 触发优先级：哪个先触发就执行哪个，执行后所有管理器都重置
  # ⚠️ 注意：当前配置中，本金保护（1%）会比剥头皮（90%）更早触发！

# 🛡️ 四重保护使用场景举例（做多）：
#
# 初始状态：
# - 抵押品: $2000 USDC（初始本金）
# - 网格: 200格，每格$0.002，区间 $1.70 - $2.10
# - 剥头皮触发点: Grid 20（200 - 200*90% = 20，约$1.738）
# - 本金保护触发点: Grid 198（200 - 200*1% = 198，约$2.096）
# - 当前价格: $2.10（Grid 200，做多准备）
#
# ========================================
# 场景1：剥头皮止盈成功（最理想）
# ========================================
# 价格走势: $2.10 → $1.90（下跌，触发剥头皮）
# 
# 1. 触发剥头皮（买单成交90%）🎯
#    - 取消所有卖单（不再平仓）
#    - 保留买单继续建仓
#    - 持仓: +90.0 ASTER（做多90个）, 成本: $2.05
#    - 挂止盈单: sell 90.0@$2.054（成本价+2格，约$2.054）
#
# 2. 价格反弹到$2.054，止盈单成交 ✅
#    - 持仓清零
#    - 网格重置并重新启动 🔄
#    - 所有管理器状态都清空
#    - 盈利: (2.054-2.05) * 90 = $0.36
#
# ========================================
# 场景2：剥头皮失效，本金保护兜底
# ========================================
# 价格走势: $2.10 → $1.90（触发剥头皮）→ $1.70（继续下跌，触发本金保护）
#
# 1. 触发剥头皮（买单成交90%）🎯
#    - 挂止盈单: sell 90.0@$2.054
#
# 2. 价格继续下跌，止盈单未成交，买单继续成交
#    - 触发本金保护（买单成交40%，相当于价格下跌到第80格）🛡️
#    - 持仓: +120.0 ASTER（做多120个）, 成本: $1.95
#    - 当前抵押品: $1820（亏损$180，因为多单浮亏）
#    - 状态: 等待回本 ⏳
#
# 3. 价格反弹到$2.10
#    - 多单盈利，抵押品增加
#    - 未实现盈利: (2.10-1.95) * 120 = $18
#    - 当前抵押品: $2020（超过初始本金$2000）✅
#    - 执行重置: 取消所有订单 → 平仓 → 重启网格 🔄
#
# ========================================
# 场景3：价格快速下跌，跳过剥头皮
# ========================================
# 价格走势: $2.10 → 快速暴跌到$1.60（第120格）
#
# 1. 直接触发本金保护（跳过剥头皮）🛡️
#    - 持仓: +150.0 ASTER（做多150个）, 成本: $1.90
#    - 当前抵押品: $1700（亏损$300）
#    - 状态: 等待回本 ⏳
#
# 2. 价格反弹到$2.10
#    - 多单大幅盈利: (2.10-1.90) * 150 = $30
#    - 当前抵押品: $2030（盈利$30）✅
#    - 执行重置: 取消所有订单 → 平仓 → 重启网格 🔄
#
# ========================================
# 场景4：价格锁定模式（智能冻结）
# ========================================
# 价格走势: $2.10 → $2.60（向上脱离，盈利方向）
#
# 1. 价格向上脱离到$2.60
#    - 价格 >= $2.50（锁定阈值）
#    - 🔒 激活价格锁定，冻结网格
#    - 保留所有订单和持仓
#    - 持仓: +80.0 ASTER（做多80个）, 成本: $2.05
#    - 未实现盈利: (2.60-2.05) * 80 = $44.00
#
# 2. 价格继续上涨到$2.80
#    - 仍处于锁定状态 🔒
#    - 卖单继续成交，持仓减少
#    - 已实现盈利继续增加
#
# 3. 价格回落到$2.40（回到网格范围）
#    - 🔓 自动解除价格锁定
#    - 恢复正常网格交易
#    - 继续挂单和成交
#
# 优势：
# ✅ 防止在大涨时过早平仓止盈
# ✅ 最大化盈利空间
# ✅ 价格回落时自动恢复交易
#
# ========================================
# 场景5：止盈模式触发（盈利保护）
# ========================================
# 持续震荡盈利场景: $2.10 ↔ $2.15 ↔ $2.08 ↔ $2.18
#
# 1. 多次网格交易，累计盈利
#    - 抵押品从 $2000 增加到 $2011
#    - 盈利率: $11 / $2000 = 0.55% > 0.5%阈值 ✅
#
# 2. 触发止盈模式 💰
#    - 取消所有订单
#    - 平仓所有持仓（市价单）
#    - 锁定盈利 $11
#    - 重置网格并重新启动 🔄
#
# ========================================
# 关键要点（做多）：
# ========================================
# ✅ 剥头皮优先：90%触发（价格下跌，买单大量成交），通过止盈单获利退出
# ✅ 本金保护兜底：40%触发（价格继续下跌），等待价格反弹回本后退出
# ✅ 止盈模式：盈利0.5%即止盈，落袋为安
# ✅ 价格锁定：价格大涨时冻结，最大化盈利空间
# ✅ 四重保险：最大化保护本金安全并锁定利润
# ✅ 自动重启：跟随价格网格自动重置，无需人工干预
# ✅ 做多逻辑：价格下跌=不利方向，需要保护；价格上涨=盈利方向

# ========================================
# 📊 做多 vs 做空对比：
# ========================================
#
# | 项目 | 做多 | 做空 |
# |------|------|------|
# | 不利方向 | 价格下跌 | 价格上涨 |
# | 有利方向 | 价格上涨 | 价格下跌 |
# | 剥头皮触发 | 买单成交90%（价格↓） | 卖单成交90%（价格↑） |
# | 剥头皮操作 | 取消卖单，挂止盈卖单 | 取消买单，挂止盈买单 |
# | 本金保护触发 | 买单成交40%（价格↓↓） | 卖单成交40%（价格↑↑） |
# | 本金保护 | 等待价格反弹回本 | 等待价格回落回本 |
# | 价格锁定条件 | 价格>=阈值（向上脱离） | 价格<=阈值（向下脱离） |
# | 盈利方式 | 价格上涨 | 价格下跌 |
#
# 核心一致：抵押品>=初始本金 = 回本（不区分做多做空）
#
# ========================================
# 💡 做多网格使用建议：
# ========================================
# 
# 1. 网格参数调整：
#    - 如果价格持续下跌，可以：
#      a. 减少 order_amount（降低单笔金额）
#      b. 增大 grid_interval（减少触发频率）
#      c. 减少 follow_grid_count（缩小网格范围）
#
# 2. 剥头皮触发百分比：
#    - 90% 比较激进（买单成交90%才触发）
#    - 可以调整为 80% 更早触发保护
#
# 3. 本金保护触发百分比：
#    - 40% 是兜底保护（买单成交40%）
#    - 可以调整为 50% 更早触发保护
#
# 4. 价格锁定阈值：
#    - 当前 $2.50（假设网格上限约$2.40）
#    - 应该设置在网格上限之上10%-20%
#    - 防止正常上涨就触发锁定
#
# 5. 止盈百分比：
#    - 当前 0.5%（保守）
#    - 可以调整为 1% 或更高
#    - 根据风险偏好调整
#

