# ==============================================================================
# 网格交易完整配置文件（做空方向）
# ==============================================================================
# 
# 🎯 当前配置：价格移动网格 + 四重保护（剥头皮 + 本金保护 + 止盈 + 价格锁定）
# 
# 📋 本文件包含所有网格模式，需要切换时取消对应注释即可：
#    ✅ 价格移动网格（当前启用）
#    📝 固定范围网格（注释中，可启用）
#    📝 马丁模式（注释中，可启用）
# 
# ==============================================================================

grid_system:
  # ============================================================================
  # 基础配置
  # ============================================================================
  exchange: "backpack"
  symbol: "HYPE_USDC_PERP"
  
  # ----------------------------------------------------------------------------
  # 网格类型选择（三选一，其他两个需注释）
  # ----------------------------------------------------------------------------
  grid_type: "follow_short"        # ✅ 当前：价格移动做空网格
  # grid_type: "short"             # 📝 备选：固定范围做空网格
  # grid_type: "martingale_short"  # 📝 备选：固定范围做空马丁网格
  
  # ============================================================================
  # 价格移动网格参数（grid_type = "follow_short" 时生效）
  # ============================================================================
  follow_grid_count: 200      # 总共200个网格
  follow_timeout: 300         # 脱离超时5分钟
  follow_distance: 2          # 脱离距离2格
  
  # ----------------------------------------------------------------------------
  # 固定范围网格参数（grid_type = "short" 或 "martingale_short" 时生效）
  # 需要启用固定范围网格时，取消下面3行注释，并注释掉上面的follow参数
  # ----------------------------------------------------------------------------
  # lower_price: 1.90          # 📝 网格下限价格
  # upper_price: 2.30          # 📝 网格上限价格
  # # 网格数量会根据 (upper_price - lower_price) / grid_interval 自动计算
  
  # ============================================================================
  # 通用网格参数（所有网格类型都需要）
  # ============================================================================
  grid_interval: 0.0022        # 每格间隔$0.002
  order_amount: 5.0           # 每格基础数量 5.0 ASTER
  
  # ----------------------------------------------------------------------------
  # 马丁模式参数（grid_type = "martingale_short" 时生效）
  # 需要启用马丁模式时，取消下面1行注释
  # ----------------------------------------------------------------------------
  # martingale_increment: 0.5  # 📝 马丁递增数量（每格增加0.5 ASTER）
  #                            #    例如：第1格5.0, 第2格5.5, 第3格6.0...
  
  # 🎯 剥头皮模式配置（第一道防线）
  scalping_enabled: true               # ✅ 启用剥头皮
  scalping_trigger_percent: 95         # 🔔 触发阈值80%（第40格）
  scalping_take_profit_grids: 2        # 📊 止盈2格
  
  # 🛡️ 本金保护模式配置（第二道防线）
  capital_protection_enabled: true     # ✅ 启用本金保护
  capital_protection_trigger_percent: 30  # 🔔 触发阈值50%（第25格）
  
  # 💰 止盈模式配置（盈利保护）
  take_profit_enabled: true            # ✅ 启用止盈模式
  take_profit_percentage: 0.004         # 🎯 止盈阈值1%（盈利超过本金1%时止盈）
  
  # 🔒 价格锁定模式配置（智能冻结）
  price_lock_enabled: true             # ✅ 启用价格锁定模式
  price_lock_threshold: 2.0            # 🎯 锁定价格阈值 $1.80
  price_lock_start_at_threshold: false  # 🆕 启动时使用阈值作为起点（仅价格移动网格FOLLOW模式生效）
  # 说明：
  # - true: 如果启动时当前价格 < 阈值，则以阈值为网格下限（期望在更高价格区间启动）
  # - false: 始终以当前价格为网格起点（默认行为）
  # - 仅对价格移动网格（FOLLOW_LONG/FOLLOW_SHORT）生效，普通网格忽略此参数
  
  # 做空网格：
  # - 当价格向下脱离网格范围时（盈利方向）
  # - 如果价格 <= $1.80，则冻结网格（不平仓止盈）
  # - 保留订单和持仓，等待价格反弹
  # - 价格回到网格范围内时，自动解除冻结
  
  # 🎯 反手挂单格子距离配置（利润优化）
  reverse_order_grid_distance: 1       # 🔥 反手挂单距离（默认1格，可自定义提高利润）
  # 说明：成交后反手挂单的格子距离
  # - 默认值1：卖单成交@$2.00 → 买单挂@$1.99（间隔1格）
  # - 设置为2：卖单成交@$2.00 → 买单挂@$1.98（间隔2格，利润提高）
  # - 设置为3：卖单成交@$2.00 → 买单挂@$1.97（间隔3格，利润更高）
  # - 推荐范围：1-5格（格数越高利润越大，但成交概率降低）
  # - 适用场景：震荡行情可适当提高，单边行情保持默认值

    # 🔍 订单健康检查间隔配置（系统维护）
  order_health_check_interval: 600     # 🕐 健康检查间隔（秒，默认300秒=5分钟）
  # 说明：定期检查订单健康状态
  # - 默认值：300秒（5分钟）
  # - 推荐范围：180-600秒（3-10分钟）
  # - 设置太短：频繁检查，可能影响性能
  # - 设置太长：问题发现不及时
  # - 实战建议：300-600秒（5-10分钟）
  
  # 四重保护说明（做空方向）：
  # 1. 剥头皮（90%）：价格上涨到第180格 → 取消买单 → 挂止盈单 → 止盈成交后重置
  # 2. 本金保护（40%）：价格继续上涨到第80格 → 等待抵押品回本 → 回本后重置
  # 3. 止盈模式（1%）：盈利超过本金1% → 平仓 → 重置网格
  # 4. 价格锁定（$1.80）：价格向下脱离 <= $1.80 → 冻结网格 → 等待价格回归
  # 
  # 触发优先级：哪个先触发就执行哪个，执行后所有管理器都重置

# 🛡️ 四重保护使用场景举例（做空）：
#
# 初始状态：
# - 抵押品: $2000 USDC（初始本金）
# - 网格: 50格，剥头皮触发点第40格，本金保护触发点第25格
# - 当前价格: $2.00（做空开仓）
#
# ========================================
# 场景1：剥头皮止盈成功（最理想）
# ========================================
# 价格走势: $2.00 → $2.80（上涨到第40格）
# 
# 1. 触发剥头皮（第40格）🎯
#    - 取消所有买单
#    - 保留卖单继续建仓
#    - 持仓: -5.0 ASTER（做空5个）, 成本: $2.20
#    - 挂止盈单: buy 5.0@$2.16（成本价-2格，平空仓）
#
# 2. 价格回落到$2.16，止盈单成交 ✅
#    - 持仓清零
#    - 网格重置并重新启动 🔄
#    - 两个管理器状态都清空
#    - 盈利: (2.20-2.16) * 5 = $0.20
#
# ========================================
# 场景2：剥头皮失效，本金保护兜底
# ========================================
# 价格走势: $2.00 → $2.80（第40格）→ $3.00（第25格）
#
# 1. 触发剥头皮（第40格）🎯
#    - 挂止盈单: buy 5.0@$2.16
#
# 2. 价格继续上涨，止盈单未成交，突破第25格
#    - 触发本金保护（第25格）🛡️
#    - 持仓: -8.0 ASTER（做空8个）, 成本: $2.30
#    - 当前抵押品: $1920（亏损$80，因为空单亏损）
#    - 状态: 等待回本 ⏳
#
# 3. 价格回落到$2.25
#    - 空单盈利，抵押品增加
#    - 当前抵押品: $2015（盈利$15）✅
#    - 执行重置: 取消所有订单 → 平仓 → 重启网格 🔄
#
# ========================================
# 场景3：价格快速上涨，跳过剥头皮
# ========================================
# 价格走势: $2.00 → 快速暴涨到$3.40（第35格）
#
# 1. 直接触发本金保护（跳过剥头皮）🛡️
#    - 持仓: -10.0 ASTER（做空10个）, 成本: $2.40
#    - 当前抵押品: $1850（亏损$150）
#    - 状态: 等待回本 ⏳
#
# 2. 价格回落到$2.10
#    - 空单大幅盈利: (2.40-2.10) * 10 = $3.00
#    - 当前抵押品: $2020（盈利$20）✅
#    - 执行重置: 取消所有订单 → 平仓 → 重启网格 🔄
#
# ========================================
# 关键要点（做空）：
# ========================================
# ✅ 剥头皮优先：80%触发（价格上涨），通过止盈单获利退出
# ✅ 本金保护兜底：50%触发（价格继续上涨），等待价格回落回本后退出
# ✅ 双重保险：最大化保护本金安全
# ✅ 自动重启：跟随价格网格自动重置，无需人工干预
# ✅ 做空逻辑：价格上涨=不利方向，需要保护；价格下跌=盈利方向

# ========================================
# 场景4：价格锁定模式（智能冻结）
# ========================================
# 价格走势: $2.00 → $1.60（向下脱离，盈利方向）
#
# 1. 价格向下脱离到$1.60
#    - 价格 <= $1.80（锁定阈值）
#    - 🔒 激活价格锁定，冻结网格
#    - 保留所有订单和持仓
#    - 持仓: -15.0 ASTER（做空15个）, 成本: $1.90
#    - 未实现盈利: (1.90-1.60) * 15 = $4.50
#
# 2. 价格继续下跌到$1.50
#    - 仍处于锁定状态 🔒
#    - 订单继续成交，持仓增加
#    - 未实现盈利继续增加
#
# 3. 价格反弹到$1.85（回到网格范围）
#    - 🔓 自动解除价格锁定
#    - 恢复正常网格交易
#    - 继续挂单和成交
#
# 优势：
# ✅ 防止在大跌时过早平仓止盈
# ✅ 最大化盈利空间
# ✅ 价格反弹时自动恢复交易
#
# ========================================
# 📊 做空 vs 做多对比：
# ========================================
#
# | 项目 | 做多 | 做空 |
# |------|------|------|
# | 不利方向 | 价格下跌 | 价格上涨 |
# | 有利方向 | 价格上涨 | 价格下跌 |
# | 触发方向 | 网格索引增大（价格↓） | 网格索引增大（价格↑） |
# | 剥头皮操作 | 取消卖单，挂止盈卖单 | 取消买单，挂止盈买单 |
# | 本金保护 | 等待价格反弹回本 | 等待价格回落回本 |
# | 价格锁定条件 | 价格>=阈值（向上脱离） | 价格<=阈值（向下脱离） |
# | 盈利方式 | 价格上涨 | 价格下跌 |
#
# 核心一致：抵押品>=初始本金 = 回本（不区分做多做空）

